###
GET http://localhost:8080/persons/by-city?city=Санкт-Петербург

###
GET http://localhost:8080/persons/by-age?age=45

###
GET http://localhost:8080/persons/by-nameandsurnameandage?name=Иван&surname=Иванов&age=25